default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    description: A tool to upgrade syntax for newer versions of Python
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
      - id: trailing-whitespace # trims trailing whitespace
      - id: check-added-large-files # prevents giant files from being committed
      - id: check-ast # simply checks whether the files parse as valid Python
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang
      - id: check-json # checks json files for parsable syntax
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable
      - id: check-merge-conflict # checks for files that contain merge conflict strings
      - id: check-yaml # checks yaml files for parsable syntax
      - id: detect-aws-credentials # detects *your* aws credentials from the aws cli credentials file
      - id: detect-private-key # detects the presence of private keys
      - id: requirements-txt-fixer # sorts entries in requirements.txt
      - id: name-tests-test # this verifies that test files are named correctly
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    description: Sort Python imports
    hooks:
      - id: isort
        args: [--profile, black, --filter-files, --line-length, "120"]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    description: "Python files formatter"
    hooks:
      - id: black
        args: [--line-length, "120"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    description: Format frontend files
    hooks:
      - id: prettier
  - repo: https://github.com/Wonqu/sort_makefile/
    rev: "0.9"
    hooks:
      - id: sort_makefile
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.16.0
    description: "Git commit message linter written in Python: it checks your commit messages for style"
    hooks:
      - id: gitlint
